### PR TITLE
to single quote styling.

### PR DESCRIPTION
**Pull request by Hattori-URD**
Double quote to single quote.
Please, check.

### CODE REVIEW

**Comment by ryoichi-obara** [comment]
Great thanks to pull request.
Here's my review result below.

Single quote is not always used except javascript code (not in file).
So, Changes ``"Sync. Byte", "Header" and "CRC8H"`` to ``'Sync. Byte', 'Header' and 'CRC8H'`` is not required
because it's just a javascript comment.
and Changes ``"${receivedSensorId}"`` to ``'${receivedSensorId}'`` is not also required
because it's a log text/message.

The other changes to single quote looks fine.

For reference, here's a coding guide below and we welcome to discuss about this guide.
https://github.com/ia-cloud/node-red-contrib-ia-cloud-fds/blob/master/coding-guide.md

**Comment by ryoichi-obara** [comment]
I think it's ok to merge, both are okay as javascript comment / log text.

**Review by ryoichi-obara — APPROVED** [review]

**Review by ryoichi-obara — APPROVED** [review]

**Comment by Hattori-URD** [comment]
Thank you for guiding the Mark Down coding guide.
I'm glad to your review.

**Comment by Hattori-URD** [comment]
There was a new version release, so I will close it once.
Thank you :D

**Comment by ryoichi-obara** [comment]
Sorry for not including v0.1.4 (I've already released), but I think it's necessary for next version v0.1.5 so reopen this pull request.

**Pull request merged**
